
package com.empleado.GUI;

import com.empleado.bo.EmpleadoBO;
import com.empleado.entity.Empleado;
import javax.swing.JOptionPane;

/**
 *
 * @author Robert
 */
public class FrmEmpelado extends javax.swing.JFrame {

    /**
     * Creates new form FrmEmpelado
     */
    private EmpleadoBO ebo = new EmpleadoBO();
    
    public FrmEmpelado() {      
    initComponents();
    listarEmpleado();  
    idMax();
        setTitle("Proyecto Final: Formulario Empleado");
        setLocationRelativeTo(null);
        setResizable(false);
    }
        
        
            public void listarEmpleado(){
            ebo.listarEmpleado(tbEmpleado);   
            }
            
            public void idMax(){
                txtIDEmpleado.setText(ebo.getMaxID()+"");
            }
    
    
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupEstadoCivil = new javax.swing.ButtonGroup();
        groupGenero = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIDEmpleado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rdCasado = new javax.swing.JRadioButton();
        rdSoltero = new javax.swing.JRadioButton();
        rdMasculino = new javax.swing.JRadioButton();
        rdFemenino = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmpleado = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 17)); // NOI18N
        jLabel1.setText("ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txtIDEmpleado.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel1.add(txtIDEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 220, -1));

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setText("Formulario Empleado");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        txtNombres.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 220, -1));

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 17)); // NOI18N
        jLabel3.setText("Nombres:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        txtApellidos.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 220, -1));

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 17)); // NOI18N
        jLabel4.setText("Apellidos:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txtCedula.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 220, -1));

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 17)); // NOI18N
        jLabel5.setText("Cedula:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 17)); // NOI18N
        jLabel6.setText("Estado Civil:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Courier New", 0, 17)); // NOI18N
        jLabel7.setText("Género:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        txtEdad.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 220, -1));

        jLabel8.setFont(new java.awt.Font("Courier New", 0, 17)); // NOI18N
        jLabel8.setText("Edad:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        groupEstadoCivil.add(rdCasado);
        rdCasado.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        rdCasado.setText("Casado");
        rdCasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdCasadoActionPerformed(evt);
            }
        });
        jPanel1.add(rdCasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        groupEstadoCivil.add(rdSoltero);
        rdSoltero.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        rdSoltero.setText("Soltero");
        rdSoltero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdSolteroActionPerformed(evt);
            }
        });
        jPanel1.add(rdSoltero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        groupGenero.add(rdMasculino);
        rdMasculino.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        rdMasculino.setText("Masculino");
        rdMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMasculinoActionPerformed(evt);
            }
        });
        jPanel1.add(rdMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        groupGenero.add(rdFemenino);
        rdFemenino.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        rdFemenino.setText("Femenino");
        rdFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFemeninoActionPerformed(evt);
            }
        });
        jPanel1.add(rdFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        tbEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEmpleadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbEmpleado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 400, 290));

        btnSalir.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, -1, -1));

        btnAgregar.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        btnModificar.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, -1, -1));

        btnLimpiar.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdCasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdCasadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdCasadoActionPerformed

    private void rdSolteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSolteroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdSolteroActionPerformed

    private void rdMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdMasculinoActionPerformed

    private void rdFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdFemeninoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:

        if(ebo.checkDuplicates(Integer.parseInt(txtIDEmpleado.getText())) == 0){
            JOptionPane.showMessageDialog(null,"ID ya existe, porfavor utilice otro ID");
            return;
        }

        if (txtIDEmpleado.getText().isEmpty() || txtNombres.getText().isEmpty() || txtApellidos.getText().isEmpty() || txtCedula.getText().isEmpty() ||txtEdad.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos ");            
        } else{
            
            char estado;
            if (rdCasado.isSelected()){
                estado = 'C';
            }else{
                estado = 'S';
            }
            
            char genero;
            if (rdFemenino.isSelected()){
                genero = 'F';
            }else{
                genero = 'M';
            }
            
            Empleado emp = new Empleado();
            emp.setIdEmpleado(Integer.parseInt(txtIDEmpleado.getText()));
            emp.setNombres(txtNombres.getText());
            emp.setApellidos(txtApellidos.getText());
            emp.setCedula(txtCedula.getText());
            emp.setEstadoCivil(estado);
            emp.setGenero(genero);
            emp.setEdad(Integer.parseInt(txtEdad.getText()));  
            String mensaje = ebo.agregarEmpleado(emp);
            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            listarEmpleado();
            
        }
        
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if (txtIDEmpleado.getText().isEmpty() || txtNombres.getText().isEmpty() || txtApellidos.getText().isEmpty() || txtCedula.getText().isEmpty() ||txtEdad.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos ");            
        } else{
            
            char estado;
            if (rdCasado.isSelected()){
                estado = 'C';
            }else{
                estado = 'S';
            }
            
            char genero;
            if (rdFemenino.isSelected()){
                genero = 'F';
            }else{
                genero = 'M';
            }
            
            Empleado emp = new Empleado();
            emp.setIdEmpleado(Integer.parseInt(txtIDEmpleado.getText()));
            emp.setNombres(txtNombres.getText());
            emp.setApellidos(txtApellidos.getText());
            emp.setCedula(txtCedula.getText());
            emp.setEstadoCivil(estado);
            emp.setGenero(genero);
            emp.setEdad(Integer.parseInt(txtEdad.getText()));  
            String mensaje = ebo.modificarEmpleado(emp);
            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            listarEmpleado();
        }
            
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (txtIDEmpleado.getText().isEmpty() || txtNombres.getText().isEmpty() || txtApellidos.getText().isEmpty() || txtCedula.getText().isEmpty() ||txtEdad.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos ");            
        } else{
            String mensaje = ebo.eliminarEmpleado(Integer.parseInt(txtIDEmpleado.getText()));
            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            listarEmpleado();
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tbEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEmpleadoMouseClicked
        // TODO add your handling code here:
        int seleccion = tbEmpleado.rowAtPoint(evt.getPoint());
        txtIDEmpleado.setText(tbEmpleado.getValueAt(seleccion, 0)+"");
        txtNombres.setText(tbEmpleado.getValueAt(seleccion, 1)+"");
        txtApellidos.setText(tbEmpleado.getValueAt(seleccion, 2)+"");
        txtCedula.setText(tbEmpleado.getValueAt(seleccion, 3)+"");
        String estado = tbEmpleado.getValueAt(seleccion, 4)+"";
        
        if (estado.equals("S")){
            rdSoltero.setSelected(true);
        }else{
            rdCasado.setSelected(true);
        }
        
        String genero = tbEmpleado.getValueAt(seleccion, 5)+"";
        if (genero.equals("M")){
            rdMasculino.setSelected(true);
        }else{
            rdFemenino.setSelected(true);
        }
        
        txtEdad.setText(tbEmpleado.getValueAt(seleccion, 6)+"");
        
   
    }//GEN-LAST:event_tbEmpleadoMouseClicked

    public void limpiar(){
        txtIDEmpleado.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtCedula.setText("");
        txtEdad.setText("");
        groupEstadoCivil.clearSelection();
        groupGenero.clearSelection();
        
         idMax();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEmpelado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEmpelado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEmpelado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEmpelado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEmpelado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup groupEstadoCivil;
    private javax.swing.ButtonGroup groupGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdCasado;
    private javax.swing.JRadioButton rdFemenino;
    private javax.swing.JRadioButton rdMasculino;
    private javax.swing.JRadioButton rdSoltero;
    private javax.swing.JTable tbEmpleado;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtIDEmpleado;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
